#compdef test-command
# Generated by picocli AutoComplete
# Version: %1$s

_picocli_test-command() {
  local line state

  _arguments -C -s \
    '-h[Show this help message and exit.]' \
    '--help[Show this help message and exit.]' \
    '-V[Print version information and exit.]' \
    '--version[Print version information and exit.]' \
    "1: :->cmds" \
    "*::arg:->args"

  case "$state" in
    cmds)
      _values "test-command command" \
        "generate-completion[Generate bash/zsh completion script for test-command.]" \
        "sub-1[What is your name]" \
        "sub-2"
      ;;
    args)
      case $line[1] in
        generate-completion)
          _picocli_test-command_generate-completion
          ;;
        sub-1)
          _picocli_test-command_sub-1
          ;;
        sub-2)
          _picocli_test-command_sub-2
          ;;
      esac
      ;;
  esac
}

_picocli_test-command_generatecompletion() {
  _arguments -s \
    '-s[Shell type: bash, zsh (default: bash)]:<shell>:'\
    '--shell[Shell type: bash, zsh (default: bash)]:<shell>:'\
    '-h[Show this help message and exit.]'\
    '--help[Show this help message and exit.]'\
    '-V[Print version information and exit.]'\
    '--version[Print version information and exit.]'
}

_picocli_test-command_sub1() {
  local line state

  _arguments -C -s \
    '-h[Show this help message and exit.]' \
    '--help[Show this help message and exit.]' \
    '-V[Print version information and exit.]' \
    '--version[Print version information and exit.]' \
    "1: :->cmds" \
    "*::arg:->args"

  case "$state" in
    cmds)
      _values "sub-1 command" \
        "sub-sub-1"
      ;;
    args)
      case $line[1] in
        sub-sub-1)
          _picocli_test-command_sub1_sub-sub-1
          ;;
      esac
      ;;
  esac
}

_picocli_test-command_sub2() {
  _arguments -s \
    '-h[Show this help message and exit.]'\
    '--help[Show this help message and exit.]'\
    '-V[Print version information and exit.]'\
    '--version[Print version information and exit.]'
}

_picocli_test-command_sub1_subsub1() {
  _arguments -s \
    '-h[Show this help message and exit.]'\
    '--help[Show this help message and exit.]'\
    '-V[Print version information and exit.]'\
    '--version[Print version information and exit.]'
}

compdef _picocli_test-command test-command
